version: "3"
services:
  nexus:
    image: sonatype/nexus3:latest
    restart: unless-stopped
    container_name: nexus
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    volumes:
      - /data/registry/nexus-data:/nexus-data
    networks:
      - registry
networks:
  registry:
